function SynchronousMotorDesignGUI
% SynchronousMotorDesignGUI
% EEE 3002 Electric Machines Design Experiment
% This MATLAB GUI calculates and explains the design problem of a
% variable-frequency controlled synchronous motor.

%% % 1. Clear workspace and create main GUI window

clc;        % Clear command window
close all;  % Close open figures

% Create main application window
fig = uifigure( ...
    'Name', 'EEE 3002 Electric Machines Design Experiment', ...
    'Position', [100 100 1350 760]);

% Create main layout: left side for inputs, right side for output tabs
mainGrid = uigridlayout(fig, [1 2]);
mainGrid.ColumnWidth = {360, '1x'};
mainGrid.RowHeight = {'1x'};
mainGrid.Padding = [15 15 15 15];
mainGrid.ColumnSpacing = 15;

%% % 2. Create input panel on the left side

% Input panel
inputPanel = uipanel(mainGrid, ...
    'Title', 'Input Parameters', ...
    'FontWeight', 'bold');

inputPanel.Layout.Row = 1;
inputPanel.Layout.Column = 1;

% Grid layout inside input panel
inputGrid = uigridlayout(inputPanel, [15 3]);
inputGrid.RowHeight = { ...
    30, 45, 45, 45, 45, 45, 45, 45, 45, 45, ...
    45, 45, 45, 45, '1x'};
inputGrid.ColumnWidth = {120, '1x', 75};
inputGrid.Padding = [10 10 10 10];
inputGrid.RowSpacing = 8;
inputGrid.ColumnSpacing = 8;

% Title text
titleLabel = uilabel(inputGrid, ...
    'Text', 'Synchronous Motor Design Inputs', ...
    'FontWeight', 'bold', ...
    'FontSize', 14);
titleLabel.Layout.Row = 1;
titleLabel.Layout.Column = [1 3];

%% % 3. Create sliders, numeric fields and dropdown menus

% Each numerical input has a slider and a numeric edit field.
% The slider is useful for quick testing, and the numeric field is useful
% for entering exact values.

inputs.VL = createSliderInput(inputGrid, 2, ...
    'Line Voltage VL (V)', 100, 1000, 410);

inputs.P = createSliderInput(inputGrid, 3, ...
    'Rated Power P (kW)', 1, 500, 100);

inputs.PF = createSliderInput(inputGrid, 4, ...
    'Power Factor PF', 0.1, 1.0, 0.8);

inputs.f = createSliderInput(inputGrid, 5, ...
    'Frequency f (Hz)', 5, 100, 50);

% Pole number is discrete, so dropdown is more suitable than a continuous slider.
poleLabel = uilabel(inputGrid, 'Text', 'Pole Number');
poleLabel.Layout.Row = 6;
poleLabel.Layout.Column = 1;

poleDropdown = uidropdown(inputGrid, ...
    'Items', {'2', '4', '6', '8', '10', '12'}, ...
    'Value', '4', ...
    'ValueChangedFcn', @(src,event) updateAll());
poleDropdown.Layout.Row = 6;
poleDropdown.Layout.Column = [2 3];

% Connection type selection
connectionLabel = uilabel(inputGrid, 'Text', 'Connection Type');
connectionLabel.Layout.Row = 7;
connectionLabel.Layout.Column = 1;

connectionDropdown = uidropdown(inputGrid, ...
    'Items', {'Y-connected', 'Delta-connected'}, ...
    'Value', 'Y-connected', ...
    'ValueChangedFcn', @(src,event) updateAll());
connectionDropdown.Layout.Row = 7;
connectionDropdown.Layout.Column = [2 3];

inputs.Xs = createSliderInput(inputGrid, 8, ...
    'Sync. Reactance Xs (ohm)', 0.1, 20, 1.8);

inputs.nMin = createSliderInput(inputGrid, 9, ...
    'Minimum Speed (rpm)', 50, 3000, 300);

inputs.nMax = createSliderInput(inputGrid, 10, ...
    'Maximum Speed (rpm)', 50, 3000, 1500);

% Power factor type selection
pfTypeLabel = uilabel(inputGrid, 'Text', 'PF Type');
pfTypeLabel.Layout.Row = 11;
pfTypeLabel.Layout.Column = 1;

pfTypeDropdown = uidropdown(inputGrid, ...
    'Items', {'Leading', 'Lagging'}, ...
    'Value', 'Leading', ...
    'ValueChangedFcn', @(src,event) updateAll());
pfTypeDropdown.Layout.Row = 11;
pfTypeDropdown.Layout.Column = [2 3];

% Calculate button
calculateButton = uibutton(inputGrid, ...
    'Text', 'Calculate', ...
    'FontWeight', 'bold', ...
    'ButtonPushedFcn', @(src,event) updateAll());
calculateButton.Layout.Row = 13;
calculateButton.Layout.Column = [1 3];

% Information label
infoLabel = uilabel(inputGrid, ...
    'Text', 'Change any input and press Calculate. The tabs show results, explanations, and graphs.', ...
    'WordWrap', 'on', ...
    'FontAngle', 'italic');
infoLabel.Layout.Row = 14;
infoLabel.Layout.Column = [1 3];

%% % 4. Create tab group for output results

tabGroup = uitabgroup(mainGrid);
tabGroup.Layout.Row = 1;
tabGroup.Layout.Column = 2;

%% % 5. Create one tab for each calculated output

% Tab 1
tabFreq = uitab(tabGroup, 'Title', 'Frequency Range');
[freqText, freqAx] = createTabContent(tabFreq);

% Tab 2
tabPhaseVoltage = uitab(tabGroup, 'Title', 'Phase Voltage');
[phaseText, phaseAx] = createTabContent(tabPhaseVoltage);

% Tab 3
tabCurrent = uitab(tabGroup, 'Title', 'Armature Current');
[currentText, currentAx] = createTabContent(tabCurrent);

% Tab 4
tabEA = uitab(tabGroup, 'Title', 'Internal Voltage EA');
[eaText, eaAx] = createTabContent(tabEA);

% Tab 5
tabRatedPmax = uitab(tabGroup, 'Title', 'Rated Maximum Power');
[ratedPmaxText, ratedPmaxAx] = createTabContent(tabRatedPmax);

% Tab 6
tabLowValues = uitab(tabGroup, 'Title', 'Low-Speed Values');
[lowValuesText, lowValuesAx] = createTabContent(tabLowValues);

% Tab 7
tabLowPmax = uitab(tabGroup, 'Title', 'Low-Speed Maximum Power');
[lowPmaxText, lowPmaxAx] = createTabContent(tabLowPmax);

% Tab 8
tabPowerSpeed = uitab(tabGroup, 'Title', 'Power Capability vs Speed');
[powerSpeedText, powerSpeedAx] = createTabContent(tabPowerSpeed);

% Run first calculation with default values
updateAll();

%% % 6. Define callback function for Calculate button

    function updateAll()
        % This function is called when the Calculate button is pressed or
        % when an input value is changed.

        %% % 7. Read all input values from the GUI

        VL = inputs.VL.edit.Value;          % Line voltage in volts
        P_kW = inputs.P.edit.Value;         % Rated power in kW
        PF = inputs.PF.edit.Value;          % Power factor
        fRated = inputs.f.edit.Value;       % Rated frequency in Hz
        poles = str2double(poleDropdown.Value);  % Number of poles
        connectionType = connectionDropdown.Value;
        Xs = inputs.Xs.edit.Value;          % Synchronous reactance in ohms
        nMin = inputs.nMin.edit.Value;      % Minimum speed in rpm
        nMax = inputs.nMax.edit.Value;      % Maximum speed in rpm
        pfType = pfTypeDropdown.Value;      % Leading or lagging

        % Make sure minimum speed is smaller than maximum speed.
        if nMin >= nMax
            uialert(fig, ...
                'Minimum speed must be smaller than maximum speed.', ...
                'Input Error');
            return;
        end

        %% % 8. Perform electrical machine calculations

        % Convert rated power from kW to W.
        P_W = P_kW * 1000;

        % Calculate minimum and maximum frequencies from synchronous speed.
        fMin = nMin * poles / 120;
        fMax = nMax * poles / 120;

        % Calculate rated synchronous speed from rated frequency.
        nRated = 120 * fRated / poles;

        % Calculate phase voltage depending on the connection type.
        if strcmp(connectionType, 'Y-connected')
            Vphase = VL / sqrt(3);
        else
            Vphase = VL;
        end

        % Calculate line current from three-phase power equation.
        I_line = P_W / (sqrt(3) * VL * PF);

        % In Y-connection, phase current equals line current.
        % In Delta-connection, phase current equals line current divided by sqrt(3).
        if strcmp(connectionType, 'Y-connected')
            IA = I_line;
        else
            IA = I_line / sqrt(3);
        end

        % Calculate power factor angle in radians.
        theta = acos(PF);

        % Define current phasor according to leading or lagging PF.
        if strcmp(pfType, 'Leading')
            IA_phasor = IA * exp(1j * theta);
        else
            IA_phasor = IA * exp(-1j * theta);
        end

        % Voltage phasor is taken as reference angle 0 degree.
        V_phasor = Vphase + 1j * 0;

        % For synchronous motor:
        % EA = Vphase - jXsIA
        EA_phasor = V_phasor - 1j * Xs * IA_phasor;

        % Magnitude and angle of internal generated voltage.
        EA_mag = abs(EA_phasor);
        EA_angle_deg = rad2deg(angle(EA_phasor));

        % Maximum power at rated speed.
        PmaxRated_W = 3 * Vphase * EA_mag / Xs;
        PmaxRated_kW = PmaxRated_W / 1000;

        % Low-speed frequency ratio.
        kLow = fMin / fRated;

        % Low-speed voltage, internal voltage, and reactance.
        VphaseLow = kLow * Vphase;
        EALow = kLow * EA_mag;
        XsLow = kLow * Xs;

        % Maximum power at low speed.
        PmaxLow_W = 3 * VphaseLow * EALow / XsLow;
        PmaxLow_kW = PmaxLow_W / 1000;

        % Speed vector for graph.
        speedVector = linspace(nMin, nMax, 100);

        % Frequency vector corresponding to speed vector.
        frequencyVector = speedVector * poles / 120;

        % Since power capability is approximately proportional to speed,
        % scale the rated maximum power according to speed.
        PmaxSpeed_kW = PmaxRated_kW * (speedVector / nRated);

        %% % 9. Update text areas with English explanations

        % Frequency Range tab text
        freqText.Value = splitlines(sprintf([ ...
            'FREQUENCY RANGE\n\n' ...
            'Given:\n' ...
            'Minimum speed = %.2f rpm\n' ...
            'Maximum speed = %.2f rpm\n' ...
            'Number of poles = %d\n\n' ...
            'Formula used:\n' ...
            'ns = 120 f / P\n' ...
            'Therefore, f = ns P / 120\n\n' ...
            'Calculation:\n' ...
            'f_min = %.2f x %d / 120 = %.2f Hz\n' ...
            'f_max = %.2f x %d / 120 = %.2f Hz\n\n' ...
            'Result:\n' ...
            'The input frequency must be varied from %.2f Hz to %.2f Hz.\n\n' ...
            'Explanation:\n' ...
            'The synchronous speed of a synchronous motor is directly proportional to the supply frequency. ' ...
            'Therefore, changing the input frequency changes the operating speed of the motor.'], ...
            nMin, nMax, poles, ...
            nMin, poles, fMin, ...
            nMax, poles, fMax, ...
            fMin, fMax));

        % Phase Voltage tab text
        phaseText.Value = splitlines(sprintf([ ...
            'PHASE VOLTAGE\n\n' ...
            'Given:\n' ...
            'Line voltage VL = %.2f V\n' ...
            'Connection type = %s\n\n' ...
            'Formula used:\n' ...
            'For Y-connection: V_phase = VL / sqrt(3)\n' ...
            'For Delta-connection: V_phase = VL\n\n' ...
            'Result:\n' ...
            'V_phase = %.2f V\n\n' ...
            'Explanation:\n' ...
            'The voltage used in the per-phase equivalent circuit depends on the winding connection. ' ...
            'For a Y-connected motor, the phase voltage is lower than the line voltage by a factor of sqrt(3). ' ...
            'For a delta-connected motor, the phase voltage is equal to the line voltage.'], ...
            VL, connectionType, Vphase));

        % Armature Current tab text
        currentText.Value = splitlines(sprintf([ ...
            'ARMATURE CURRENT\n\n' ...
            'Given:\n' ...
            'Rated power = %.2f kW\n' ...
            'Line voltage = %.2f V\n' ...
            'Power factor = %.2f\n' ...
            'Connection type = %s\n\n' ...
            'Formula used:\n' ...
            'P = sqrt(3) VL IL PF\n' ...
            'IL = P / (sqrt(3) VL PF)\n\n' ...
            'Calculation:\n' ...
            'IL = %.2f / (sqrt(3) x %.2f x %.2f)\n\n' ...
            'Result:\n' ...
            'Line current IL = %.2f A\n' ...
            'Armature phase current IA = %.2f A\n\n' ...
            'Explanation:\n' ...
            'The armature current is found from the three-phase power equation. ' ...
            'For Y-connection, the phase current is equal to the line current. ' ...
            'For delta-connection, the phase current is the line current divided by sqrt(3).'], ...
            P_kW, VL, PF, connectionType, ...
            P_W, VL, PF, ...
            I_line, IA));

        % Internal Voltage EA tab text
        eaText.Value = splitlines(sprintf([ ...
            'INTERNAL GENERATED VOLTAGE EA\n\n' ...
            'Given:\n' ...
            'V_phase = %.2f V\n' ...
            'IA = %.2f A\n' ...
            'Xs = %.2f ohm\n' ...
            'Power factor = %.2f %s\n\n' ...
            'Formula used:\n' ...
            'EA = V_phase - j Xs IA\n\n' ...
            'Power factor angle:\n' ...
            'theta = cos^-1(PF) = %.2f degrees\n\n' ...
            'Result:\n' ...
            '|EA| = %.2f V\n' ...
            'angle(EA) = %.2f degrees\n\n' ...
            'Explanation:\n' ...
            'The internal generated voltage is calculated using the per-phase synchronous motor voltage equation. ' ...
            'The current angle depends on whether the power factor is leading or lagging. ' ...
            'A leading power factor means that current leads the terminal voltage, while a lagging power factor means that current lags the terminal voltage.'], ...
            Vphase, IA, Xs, PF, pfType, ...
            rad2deg(theta), EA_mag, EA_angle_deg));

        % Rated Maximum Power tab text
        ratedPmaxText.Value = splitlines(sprintf([ ...
            'MAXIMUM POWER AT RATED SPEED\n\n' ...
            'Given:\n' ...
            'V_phase = %.2f V\n' ...
            '|EA| = %.2f V\n' ...
            'Xs = %.2f ohm\n\n' ...
            'Formula used:\n' ...
            'Pmax = 3 V_phase EA / Xs\n\n' ...
            'Calculation:\n' ...
            'Pmax = 3 x %.2f x %.2f / %.2f\n\n' ...
            'Result:\n' ...
            'Pmax,rated = %.2f kW\n\n' ...
            'Explanation:\n' ...
            'The maximum power of a synchronous motor is proportional to the terminal phase voltage and the internal generated voltage. ' ...
            'It is inversely proportional to the synchronous reactance.'], ...
            Vphase, EA_mag, Xs, ...
            Vphase, EA_mag, Xs, ...
            PmaxRated_kW));

        % Low-Speed Values tab text
        lowValuesText.Value = splitlines(sprintf([ ...
            'LOW-SPEED VALUES\n\n' ...
            'Given:\n' ...
            'Minimum speed = %.2f rpm\n' ...
            'Rated frequency = %.2f Hz\n' ...
            'Low-speed frequency = %.2f Hz\n\n' ...
            'Frequency ratio:\n' ...
            'k = f_low / f_rated = %.2f / %.2f = %.4f\n\n' ...
            'Formulas used:\n' ...
            'V_phase,low = k V_phase\n' ...
            'EA,low = k EA\n' ...
            'Xs,low = k Xs\n\n' ...
            'Results:\n' ...
            'V_phase,low = %.2f V\n' ...
            'EA,low = %.2f V\n' ...
            'Xs,low = %.2f ohm\n\n' ...
            'Explanation:\n' ...
            'In variable-frequency control, the V/f ratio is kept approximately constant to avoid magnetic saturation. ' ...
            'Since synchronous reactance is proportional to frequency, Xs also decreases at lower frequency.'], ...
            nMin, fRated, fMin, ...
            fMin, fRated, kLow, ...
            VphaseLow, EALow, XsLow));

        % Low-Speed Maximum Power tab text
        lowPmaxText.Value = splitlines(sprintf([ ...
            'MAXIMUM POWER AT LOW SPEED\n\n' ...
            'Given:\n' ...
            'V_phase,low = %.2f V\n' ...
            'EA,low = %.2f V\n' ...
            'Xs,low = %.2f ohm\n\n' ...
            'Formula used:\n' ...
            'Pmax,low = 3 V_phase,low EA,low / Xs,low\n\n' ...
            'Calculation:\n' ...
            'Pmax,low = 3 x %.2f x %.2f / %.2f\n\n' ...
            'Result:\n' ...
            'Pmax,low = %.2f kW\n\n' ...
            'Explanation:\n' ...
            'At lower speed, voltage, internal generated voltage, and synchronous reactance decrease with frequency. ' ...
            'As a result, the maximum power capability also decreases approximately in proportion to speed.'], ...
            VphaseLow, EALow, XsLow, ...
            VphaseLow, EALow, XsLow, ...
            PmaxLow_kW));

        % Power Capability vs Speed tab text
        powerSpeedText.Value = splitlines(sprintf([ ...
            'POWER CAPABILITY VS SPEED\n\n' ...
            'Main idea:\n' ...
            'With constant V/f control:\n' ...
            'V_phase is proportional to frequency.\n' ...
            'EA is proportional to frequency.\n' ...
            'Xs is proportional to frequency.\n\n' ...
            'Formula:\n' ...
            'Pmax = 3 V_phase EA / Xs\n\n' ...
            'Since V_phase, EA, and Xs all change with frequency, the maximum power capability becomes approximately proportional to speed.\n\n' ...
            'Result:\n' ...
            'Pmax is approximately proportional to motor speed.\n\n' ...
            'At %.2f rpm: Pmax = %.2f kW\n' ...
            'At %.2f rpm: Pmax = %.2f kW\n\n' ...
            'Explanation:\n' ...
            'As the motor speed increases, the available power capability increases nearly linearly. ' ...
            'This is why low-speed operation provides lower maximum power capability than rated-speed operation.'], ...
            nMin, PmaxLow_kW, nMax, PmaxRated_kW * (nMax / nRated)));

        %% % 10. Plot graphs on the related tabs

        % Frequency Range graph
        cla(freqAx);
        plot(freqAx, speedVector, frequencyVector, 'LineWidth', 2);
        grid(freqAx, 'on');
        xlabel(freqAx, 'Speed (rpm)');
        ylabel(freqAx, 'Frequency (Hz)');
        title(freqAx, 'Speed vs Frequency');

        % Phase Voltage graph
        cla(phaseAx);
        yVoltage = VL / sqrt(3);
        deltaVoltage = VL;
        bar(phaseAx, categorical({'Y Phase Voltage', 'Delta Phase Voltage'}), ...
            [yVoltage, deltaVoltage]);
        grid(phaseAx, 'on');
        ylabel(phaseAx, 'Voltage (V)');
        title(phaseAx, 'Phase Voltage Comparison');

        % Armature Current graph
        cla(currentAx);
        pfVector = linspace(0.1, 1.0, 100);
        IlineVector = P_W ./ (sqrt(3) * VL .* pfVector);

        if strcmp(connectionType, 'Y-connected')
            IA_vector = IlineVector;
        else
            IA_vector = IlineVector / sqrt(3);
        end

        plot(currentAx, pfVector, IA_vector, 'LineWidth', 2);
        grid(currentAx, 'on');
        xlabel(currentAx, 'Power Factor');
        ylabel(currentAx, 'Armature Current IA (A)');
        title(currentAx, 'Armature Current vs Power Factor');

        % Internal Voltage EA phasor graph
        cla(eaAx);
        hold(eaAx, 'on');

        % Draw voltage phasor
        quiver(eaAx, 0, 0, real(V_phasor), imag(V_phasor), 0, 'LineWidth', 2);

        % Draw jXsIA voltage drop phasor
        jXsIA = 1j * Xs * IA_phasor;
        quiver(eaAx, 0, 0, real(jXsIA), imag(jXsIA), 0, 'LineWidth', 2);

        % Draw EA phasor
        quiver(eaAx, 0, 0, real(EA_phasor), imag(EA_phasor), 0, 'LineWidth', 2);

        hold(eaAx, 'off');
        grid(eaAx, 'on');
        axis(eaAx, 'equal');
        xlabel(eaAx, 'Real Axis');
        ylabel(eaAx, 'Imaginary Axis');
        title(eaAx, 'Phasor Diagram');
        legend(eaAx, {'V phase', 'jXsIA', 'EA'}, 'Location', 'best');

        % Rated maximum power graph
        cla(ratedPmaxAx);
        EA_range = linspace(0.5 * EA_mag, 1.5 * EA_mag, 100);
        Pmax_range_kW = (3 * Vphase .* EA_range ./ Xs) / 1000;
        plot(ratedPmaxAx, EA_range, Pmax_range_kW, 'LineWidth', 2);
        grid(ratedPmaxAx, 'on');
        xlabel(ratedPmaxAx, 'EA (V)');
        ylabel(ratedPmaxAx, 'Pmax (kW)');
        title(ratedPmaxAx, 'Maximum Power vs EA');

        % Low-speed values graph
        cla(lowValuesAx);
        bar(lowValuesAx, categorical({'Vphase', 'EA', 'Xs'}), ...
            [VphaseLow, EALow, XsLow]);
        grid(lowValuesAx, 'on');
        ylabel(lowValuesAx, 'Value');
        title(lowValuesAx, 'Low-Speed Values');

        % Low-speed maximum power comparison graph
        cla(lowPmaxAx);
        bar(lowPmaxAx, categorical({'Low-Speed Pmax', 'Rated Pmax'}), ...
            [PmaxLow_kW, PmaxRated_kW]);
        grid(lowPmaxAx, 'on');
        ylabel(lowPmaxAx, 'Power (kW)');
        title(lowPmaxAx, 'Low-Speed and Rated Maximum Power');

        % Power capability vs speed graph
        cla(powerSpeedAx);
        plot(powerSpeedAx, speedVector, PmaxSpeed_kW, 'LineWidth', 2);
        grid(powerSpeedAx, 'on');
        xlabel(powerSpeedAx, 'Speed (rpm)');
        ylabel(powerSpeedAx, 'Maximum Power Capability (kW)');
        title(powerSpeedAx, 'Power Capability vs Speed');
    end

%% Helper function: create slider and numeric edit field

    function inputStruct = createSliderInput(parentGrid, rowNumber, labelText, minValue, maxValue, defaultValue)
        % This helper function creates one input row.
        % Each input row contains:
        % 1) A label
        % 2) A slider
        % 3) A numeric edit field

        % Create label
        lbl = uilabel(parentGrid, 'Text', labelText);
        lbl.Layout.Row = rowNumber;
        lbl.Layout.Column = 1;

        % Create slider
        sld = uislider(parentGrid, ...
            'Limits', [minValue maxValue], ...
            'Value', defaultValue);
        sld.Layout.Row = rowNumber;
        sld.Layout.Column = 2;

        % Create numeric edit field
        edt = uieditfield(parentGrid, 'numeric', ...
            'Limits', [minValue maxValue], ...
            'Value', defaultValue);
        edt.Layout.Row = rowNumber;
        edt.Layout.Column = 3;

        % When slider changes, update numeric field and recalculate.
        sld.ValueChangedFcn = @(src,event) sliderChanged(src, edt);

        % When numeric field changes, update slider and recalculate.
        edt.ValueChangedFcn = @(src,event) editChanged(src, sld);

        % Store handles in a struct
        inputStruct.label = lbl;
        inputStruct.slider = sld;
        inputStruct.edit = edt;
    end

%% Helper function: slider callback

    function sliderChanged(sliderObj, editObj)
        % This function synchronizes the numeric field with the slider.
        editObj.Value = sliderObj.Value;
        updateAll();
    end

%% Helper function: numeric edit field callback

    function editChanged(editObj, sliderObj)
        % This function synchronizes the slider with the numeric field.
        sliderObj.Value = editObj.Value;
        updateAll();
    end

%% Helper function: create tab content

    function [txt, ax] = createTabContent(parentTab)
        % This helper function creates the common structure of each tab:
        % left side: English explanation text
        % right side: graph area

        tabGrid = uigridlayout(parentTab, [1 2]);
        tabGrid.ColumnWidth = {'1x', '1.2x'};
        tabGrid.RowHeight = {'1x'};
        tabGrid.Padding = [15 15 15 15];
        tabGrid.ColumnSpacing = 15;

        % Text area for explanation and calculation steps
        txt = uitextarea(tabGrid, ...
            'Editable', 'off', ...
            'FontName', 'Consolas', ...
            'FontSize', 13);
        txt.Layout.Row = 1;
        txt.Layout.Column = 1;

        % Axes area for graph
        ax = uiaxes(tabGrid);
        ax.Layout.Row = 1;
        ax.Layout.Column = 2;
    end

end